version: "3.8"
#
#services:
#  postgres:
#    image: postgres:16-alpine
#    container_name: ts-postgres
#    environment:
#      POSTGRES_DB: tsystem
#      POSTGRES_USER: app
#      POSTGRES_PASSWORD: app
#    ports:
#      - "5432:5432"
#    restart: unless-stopped

services:
  postgres:
    image: postgres:16-alpine
    container_name: ts-postgres
    environment:
      POSTGRES_DB: tsystem
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d tsystem"]
      interval: 5s
      timeout: 3s
      retries: 30

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: ts-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: ts-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: ts-logstash
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      # твой pipeline для тикетов
      - ./logstash/logstash-tickets.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      # JDBC-драйвер PostgreSQL (скачивать .jar и положить в ./drivers)
      - ./drivers/postgresql.jar:/usr/share/logstash/lib/postgresql.jar:ro
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "5044:5044"
    restart: unless-stopped
    labels:
      org.springframework.boot.readiness-check.tcp.disable: "true"

